name: testpalha
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5625
  lightness: 0.706204426009208
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
