name: testpalha
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.42727739084511995
  lightness: 0.706204426009208
  saturation: 0.36585306422784925
  rhythmicContrast: 0.2776025019120425
purpose: []
