name: testpalha
favicon: null
layout_spectrum: 0.53568
typography_spectrum: 0.06401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aacce7'
    - '#e08e5e'
    - '#a52383'
    - '#0e1714'
    - '#039d7a'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
